# fly.toml app configuration file generated for daily-games-score on 2023-04-30T23:23:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "daily-games-score"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
